// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz3OxpcZPmFfUqp7avyeJ2EG5mV6CCT3c',
    appId: '1:307561831847:web:e568cc3af239b9cb116a82',
    messagingSenderId: '307561831847',
    projectId: 'prak-mobile-e56c3',
    authDomain: 'prak-mobile-e56c3.firebaseapp.com',
    storageBucket: 'prak-mobile-e56c3.appspot.com',
    measurementId: 'G-7W5KHNHTPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdkzfnjdKDjaJXqTnPko0C9Ih1__-0AFA',
    appId: '1:307561831847:android:97c661c7aaac4e97116a82',
    messagingSenderId: '307561831847',
    projectId: 'prak-mobile-e56c3',
    storageBucket: 'prak-mobile-e56c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFOeaoKKaKgeFkAHfuloK99csJFAok90Q',
    appId: '1:307561831847:ios:122757ff1d905855116a82',
    messagingSenderId: '307561831847',
    projectId: 'prak-mobile-e56c3',
    storageBucket: 'prak-mobile-e56c3.appspot.com',
    iosBundleId: 'com.example.onlineshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFOeaoKKaKgeFkAHfuloK99csJFAok90Q',
    appId: '1:307561831847:ios:f84d5851fdcfe056116a82',
    messagingSenderId: '307561831847',
    projectId: 'prak-mobile-e56c3',
    storageBucket: 'prak-mobile-e56c3.appspot.com',
    iosBundleId: 'com.example.onlineshop.RunnerTests',
  );
}
